#! /bin/sh
# /usr/lib/emacsen-common/packages/remove/flim
set -e

FLAVOR=$1
PACKAGE=flim

case $FLAVOR in
    emacs|emacs19|mule2)
    exit 0
    ;;
esac

ELCDIR=/usr/share/$FLAVOR/site-lisp/$PACKAGE

echo "remove/$PACKAGE: purging byte-compiled files for $FLAVOR"
rm -rf "$ELCDIR"
exit 0
