#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
  install-info --quiet --section "Emacs" "MIME (en)" \
    --menuentry=FLIM-en /usr/share/info/mime-en.info.gz
  install-info --quiet --section "Emacs" "MIME (ja)" \
    --menuentry=FLIM-ja /usr/share/info/mime-ja.info.gz
fi

#DEBHELPER#
