#!/bin/sh
set -e

if [ "$1" = remove ] || [ "$1" = upgrade ]; then
  install-info --quiet --remove /usr/share/info/mime-en.info.gz
  install-info --quiet --remove /usr/share/info/mime-ja.info.gz
fi

#DEBHELPER#
